### ISSUE TITLE
Release version w/ Typescript v4

### ISSUE THREAD

**Issue by vcapretz** [wcandillon/eslint-config-react-native-wcandillon#158]
Hey 👋 

I see that the dependabot already bumped TS to version 4+, but there's not associated release with it, would you mind releasing a new npm version so I can avoid having duplicate dependencies of TS in my project please? 

Thanks in advance, take care 😄

**Comment by wcandillon** [comment]
Sounds good!

**Comment by wcandillon** [comment]
published @3.3.4

**Comment by vcapretz** [comment]
Thank you!! 😄
