### ISSUE TITLE
Duplicated object key

### ISSUE THREAD

**Issue by a-r-i-e-l** [wcandillon/eslint-config-react-native-wcandillon#168]
not sure whether it was intended or not but I wanted to point this out just in case :)

-------------
https://github.com/wcandillon/eslint-config-react-native-wcandillon/blob/61ca88474b3c64d39c071bce114b49307324b965/index.js#L55

https://github.com/wcandillon/eslint-config-react-native-wcandillon/blob/61ca88474b3c64d39c071bce114b49307324b965/index.js#L65
-------------

-------------
https://github.com/wcandillon/eslint-config-react-native-wcandillon/blob/61ca88474b3c64d39c071bce114b49307324b965/index.js#L59

https://github.com/wcandillon/eslint-config-react-native-wcandillon/blob/61ca88474b3c64d39c071bce114b49307324b965/index.js#L67
-------------

-------------
https://github.com/wcandillon/eslint-config-react-native-wcandillon/blob/61ca88474b3c64d39c071bce114b49307324b965/index.js#L61

https://github.com/wcandillon/eslint-config-react-native-wcandillon/blob/61ca88474b3c64d39c071bce114b49307324b965/index.js#L71
-------------

**Comment by wcandillon** [comment]
Thks for noticing that!

**Comment by a-r-i-e-l** [comment]
Not sure about this but I guess in order to have this rule working

  "react-native/no-unused-styles": 2

You might need to add react-native to your pluggings array

plugins": ["import"],


Cheers
And merry Christmas
