### ISSUE TITLE
Error while installing this package

### ISSUE THREAD

**Issue by zagoorland** [wcandillon/eslint-config-react-native-wcandillon#249]
Hello. I tried to install this package, but I've got this error:
`error An unexpected error occurred: "could not find a copy of prettier to link in /Users/Me/Documents/My Stuff/expo-typescript-template/node_modules/@react-native-community/eslint-config/node_modules".`

I'm using ESLint 8.16 btw.

I would be grateful for some suggestions, thanks!

**Comment by wcandillon** [comment]
this is fixed finally :)

**Comment by zagoorland** [comment]
Thanks!
